kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-first
spec:
  selector:
    matchLabels:
      app: web-first
  replicas: 4
  template:
    metadata:
      labels:
        app: web-first
    spec:
      containers:
      - name: web-first
        image: leonardoalvesprates/web-first:v0.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080