allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: web
parameters:
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  recurringJobSelector: '[
    {
      "name":"web",
      "isGroup":false
    }
  ]'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate

